services:
  telegram-bot:
    image: python:3.10-alpine
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "apk add --no-cache ffmpeg bash build-base libffi-dev tesseract-ocr && pip install -r requirements.txt && python bot.py"
    restart: unless-stopped
